<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- propiedades del lidar -->
    <xacro:property name="lid_radius" value="0.04267" />
    <xacro:property name="lid_length" value="0.05867" />

    <!-- descripcion de los links del lidar-->
    <link name="lidar_base">
        <collision>
            <origin xyz="0 0 ${0.5 * lid_length}" rpy="0 0 0"/>
            <geometry>
                <<cylinder radius="${lid_radius}" length="${lid_length}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${0.5 * lid_length}" rpy="0 0 0"/>
            <geometry>
                <<cylinder radius="${lid_radius}" length="${lid_length}"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 ${0.5 * lid_length}" rpy="0 0 0"/>
            <mass value="0.01"/>
            <inertia
                ixx="0.0" ixy="0.0" ixz="0.0"
                iyy="${(0.015 * palm_length * palm_length)/12}" iyz="0.0"
                izz="${(0.015 * palm_length * palm_length)/12}"/>
        </inertial>
    </link>


    <link name="lidar_base">
        <collision>
            <origin xyz="0 0 ${1.5 * lid_length}" rpy="0 0 0"/>
            <geometry>
                <<cylinder radius="${lid_radius}" length="0.07357"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${1.5 * lid_length}" rpy="0 0 0"/>
            <geometry>
                <<cylinder radius="${lid_radius}" length="0.07357"/>
            </geometry>
        </visual>
    </link>
    
    <!-- descripcion de los joints del gripper-->
     <joint name="left_joint" type="revolute">
        <parent link="gripper_palm"/>
        <child link="gripper_left_finger"/>
        <origin xyz="0.06 0 -0.09" rpy="0 0 0"/>
            <limit lower="-1" upper="1" effort="10" velocity="3"/>
            <axis xyz="0 1 0"/>
     </joint>
</robot>